- id: BLW-OFAG-UFAG-FOAG
  shortId: BLW
  githubRepo: blw-ofag-ufag/metadata
  branch: main

- id: ROLAND-TEST
  shortId: ROLAND
  githubRepo: bar9/metadata-publisher-test
  branch: main

#- id: BLV-OSAV-USAV-FSVO
#  shortId: BLV
#  githubRepo: blv-osav-usav/metadata
#  branch: main
