import {Injectable} from '@angular/core';
import {AbstractControl, ValidatorFn} from '@angular/forms';
import {TranslateService} from '@ngx-translate/core';
import {ParsedValidationSchema, SchemaParserUtil} from './schema-parser.util';
import {ValidationSchemaFetcherService, SchemaConfig} from './validation-schema-fetcher.service';
import {BehaviorSubject, Observable, forkJoin, of} from 'rxjs';
import {map, tap} from 'rxjs/operators';
import * as schemaConfigs from '../../codegen/schemas.json';

export type ValidationSchemaType = 'base' | 'i14y' | 'ods';

export interface ValidationRule {
	required: boolean;
	validators: ValidatorFn[];
	pattern?: string;
	minLength?: number;
	maxLength?: number;
	customMessage?: string;
}

export interface FieldValidationGroup {
	[fieldKey: string]: ValidationRule;
}

export interface ValidationSchema {
	id: ValidationSchemaType;
	name: string;
	color: string;
	alertType: 'info' | 'warning' | 'error';
	fields: FieldValidationGroup;
	parsedSchema: ParsedValidationSchema;
}

@Injectable({
	providedIn: 'root'
})
export class ValidationSchemaService {
	private readonly schemas: Map<ValidationSchemaType, ValidationSchema> = new Map();
	private readonly schemasLoaded$ = new BehaviorSubject<boolean>(false);
	private readonly schemaLoadError$ = new BehaviorSubject<string | null>(null);
	private readonly autoGeneratedFields = ['dct:identifier'];

	constructor(
		private readonly translateService: TranslateService,
		private readonly schemaFetcher: ValidationSchemaFetcherService
	) {
		this.initializeSchemas();
	}

	/**
	 * Get validation schema by type
	 */
	getSchema(type: ValidationSchemaType): ValidationSchema | undefined {
		return this.schemas.get(type);
	}

	/**
	 * Get all available schemas
	 */
	getAllSchemas(): ValidationSchema[] {
		return Array.from(this.schemas.values());
	}

	/**
	 * Get validation rules for a specific field in a schema
	 */
	getFieldValidation(schemaType: ValidationSchemaType, fieldKey: string): ValidationRule | undefined {
		const schema = this.schemas.get(schemaType);
		return schema?.fields[fieldKey];
	}

	/**
	 * Get combined validators for a field across multiple active schemas
	 */
	getCombinedValidators(fieldKey: string, activeSchemas: ValidationSchemaType[]): ValidatorFn[] {
		const allValidators: ValidatorFn[] = [];

		activeSchemas.forEach(schemaType => {
			const fieldValidation = this.getFieldValidation(schemaType, fieldKey);
			if (fieldValidation) {
				allValidators.push(...fieldValidation.validators);
			}
		});

		return allValidators;
	}

	/**
	 * Check if field is required in any of the active schemas
	 */
	isFieldRequired(fieldKey: string, activeSchemas: ValidationSchemaType[]): boolean {
		return activeSchemas.some(schemaType => {
			const fieldValidation = this.getFieldValidation(schemaType, fieldKey);
			return fieldValidation?.required || false;
		});
	}

	/**
	 * Get validation errors for a specific schema
	 */
	getSchemaValidationErrors(schemaType: ValidationSchemaType, formValue: unknown): string[] {
		const schema = this.schemas.get(schemaType);
		if (!schema) return [];

		const errors: string[] = [];

		Object.entries(schema.fields).forEach(([fieldKey, validation]) => {
			// Skip auto-generated fields
			if (this.autoGeneratedFields.includes(fieldKey)) {
				return;
			}

			const fieldValue = this.getNestedFieldValue(formValue, fieldKey);

			// Check required validation
			if (validation.required) {
				if (!fieldValue || (Array.isArray(fieldValue) && fieldValue.length === 0)) {
					const fieldName = this.getTranslatedFieldName(fieldKey);
					errors.push(validation.customMessage || `${fieldName} is required for ${schema.name}`);
				}
			}

			// Check all validators (including multilingual)
			if (validation.validators && validation.validators.length > 0) {
				validation.validators.forEach(validator => {
					const fieldControl = {value: fieldValue};
					const validationResult = validator(fieldControl as AbstractControl);
					if (validationResult) {
						console.log(`Base schema validation failed for ${fieldKey}:`, {
							value: fieldValue,
							result: validationResult
						});
						const errorMessage = this.getValidationErrorMessage(fieldKey, validationResult, schema.name);
						if (errorMessage && !errors.includes(errorMessage)) {
							errors.push(errorMessage);
						}
					}
				});
			}
		});

		return errors;
	}

	/**
	 * Get filtered validation errors for a schema (excluding fields already covered by base schema)
	 */
	getFilteredSchemaValidationErrors(schemaType: ValidationSchemaType, formValue: unknown): string[] {
		if (schemaType === 'base') {
			// For base schema, show all errors
			return this.getSchemaValidationErrors(schemaType, formValue);
		}

		const schema = this.schemas.get(schemaType);
		const baseSchema = this.schemas.get('base');
		if (!schema || !baseSchema) return [];

		const errors: string[] = [];

		// For additional schemas (i14y, ods), show errors for fields that:
		// 1. Are required in this schema but not required in base schema, OR
		// 2. Have additional validation beyond base requirements
		Object.entries(schema.fields).forEach(([fieldKey, validation]) => {
			// Skip auto-generated fields
			if (this.autoGeneratedFields.includes(fieldKey)) {
				return;
			}

			const baseValidation = baseSchema.fields[fieldKey];
			const isRequiredInBase = baseValidation?.required || false;
			const isRequiredInSchema = validation.required;

			// Check if this field is newly required or has additional validation
			const isNewlyRequired = isRequiredInSchema && !isRequiredInBase;
			const hasAdditionalValidation = validation.validators.length > 1 || validation.customMessage;

			if (isNewlyRequired || hasAdditionalValidation) {
				// Check for required field validation
				if (isRequiredInSchema) {
					const fieldValue = this.getNestedFieldValue(formValue, fieldKey);
					if (!fieldValue || (Array.isArray(fieldValue) && fieldValue.length === 0)) {
						const fieldName = this.getTranslatedFieldName(fieldKey);
						errors.push(validation.customMessage || `${fieldName} is required for ${schema.name}`);
					}
				}

				// Check for additional validation errors (like multilingual validation)
				if (hasAdditionalValidation) {
					validation.validators.forEach(validator => {
						const fieldControl = {value: this.getNestedFieldValue(formValue, fieldKey)};
						const validationResult = validator(fieldControl as AbstractControl);
						if (validationResult) {
							console.log(`Validation failed for ${fieldKey}:`, validationResult);
							const errorMessage = validation.customMessage ||
								this.getValidationErrorMessage(fieldKey, validationResult, schema.name);
							if (errorMessage && !errors.includes(errorMessage)) {
								errors.push(errorMessage);
							}
						}
					});
				}
			}
		});

		return errors;
	}

	private initializeSchemas(): void {
		// Load schema configurations
		const configs = (schemaConfigs as any).default as SchemaConfig[];

		// Fetch all schemas dynamically
		this.schemaFetcher.fetchAllSchemas(configs).subscribe({
			next: (fetchedSchemas) => {
				fetchedSchemas.forEach((config, id) => {
					// Filter out auto-generated fields from the schema before parsing
					const filteredSchema = this.filterAutoGeneratedFields(config.schema);
					const parsed = SchemaParserUtil.parseSchema(filteredSchema);

					this.schemas.set(id as ValidationSchemaType, {
						id: id as ValidationSchemaType,
						name: config.name,
						color: config.color,
						alertType: config.alertType,
						fields: this.convertParsedSchemaToFields(parsed),
						parsedSchema: parsed
					});
				});
				this.schemasLoaded$.next(true);
			},
			error: (error) => {
				console.error('Failed to load validation schemas:', error);
				// Set error message for UI
				const errorMessage = this.translateService.instant('modify.auth.form.errors.schemaLoadFailed');
				this.schemaLoadError$.next(errorMessage);
				// Initialize with minimal schemas on error
				this.initializeFallbackSchemas();
				this.schemasLoaded$.next(true);
			}
		});
	}

	/**
	 * Filter out auto-generated fields from schema required fields
	 */
	private filterAutoGeneratedFields(schema: any): any {
		if (!schema || !schema.required) return schema;

		return {
			...schema,
			required: schema.required.filter((field: string) =>
				!this.autoGeneratedFields.includes(field)
			)
		};
	}

	/**
	 * Initialize fallback schemas when fetching fails
	 */
	private initializeFallbackSchemas(): void {
		// Minimal base schema
		this.schemas.set('base', {
			id: 'base',
			name: 'Base Requirements (Offline)',
			color: '#ff9800',
			alertType: 'warning',
			fields: {},
			parsedSchema: {
				requiredFields: [],
				recommendedFields: [],
				fields: new Map()
			}
		});
	}

	/**
	 * Check if schemas are loaded
	 */
	isLoaded(): Observable<boolean> {
		return this.schemasLoaded$.asObservable();
	}

	/**
	 * Get schema load error if any
	 */
	getLoadError(): Observable<string | null> {
		return this.schemaLoadError$.asObservable();
	}

	/**
	 * Retry loading schemas
	 */
	retryLoadingSchemas(): void {
		this.schemaLoadError$.next(null);
		this.initializeSchemas();
	}

	/**
	 * Convert parsed schema fields to ValidationRule format
	 */
	private convertParsedSchemaToFields(parsedSchema: ParsedValidationSchema): FieldValidationGroup {
		const fields: FieldValidationGroup = {};

		parsedSchema.fields.forEach((fieldData, fieldKey) => {
			fields[fieldKey] = {
				required: fieldData.required,
				validators: fieldData.validators,
				pattern: fieldData.pattern,
				minLength: fieldData.minLength,
				maxLength: fieldData.maxLength,
				customMessage: fieldData.customMessage
			};
		});

		return fields;
	}

	/**
	 * Get translated field name
	 */
	private getTranslatedFieldName(fieldKey: string): string {
		const translationKey = `labels.${fieldKey}`;
		const translated = this.translateService.instant(translationKey);
		// If translation is not found, return the field key without the prefix
		return translated === translationKey ? fieldKey.replace(/^[^:]+:/, '') : translated;
	}

	/**
	 * Get human-readable error message from validation result
	 */
	private getValidationErrorMessage(fieldKey: string, validationResult: unknown, schemaName: string): string {
		const fieldName = this.getTranslatedFieldName(fieldKey);
		const result = validationResult as Record<string, unknown>;

		if (result['multilingualRequired']) {
			const error = result['multilingualRequired'] as {missingLanguages: string[]; requiredPattern?: string};
			const langText = error.missingLanguages.map((lang: string) => lang.toUpperCase()).join(', ');
			const patternText = error.requiredPattern ? ` (${error.requiredPattern})` : '';

			// More specific error message for title field
			if (fieldKey === 'dct:title' && error.requiredPattern) {
				return `${fieldName}: ${langText} text must be ${error.requiredPattern}`;
			}

			return `${fieldName} must have text in ${langText}${patternText}`;
		}

		if (result['required']) {
			return `${fieldName} is required for ${schemaName}`;
		}

		if (result['pattern']) {
			return `${fieldName} format is invalid for ${schemaName}`;
		}

		return `${fieldName} has validation errors for ${schemaName}`;
	}

	/**
	 * Get nested field value from form object
	 */
	private getNestedFieldValue(obj: unknown, path: string): unknown {
		return path.split('.').reduce((current, key) => (current as Record<string, unknown>)?.[key], obj);
	}
}