name: Deploy GitHub Page

on:
  workflow_dispatch:  # Allows manual triggering from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      # Add steps here to build your site, e.g., install dependencies, build static files

      - name: Deploy to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Adjust based on your build output directory
