name: Build and Deploy Script
on:
    push:
        branches:
            - develop
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v2
            -   name: Adding Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: 22
            -   name: Install Dependencies
                run: npm install
            -   name: Build Angular App
                run: npm run build
            -   name: Set Git identity
                run: |
                    git config user.name "github-actions[bot]"
                    git config user.email "github-actions[bot]@users.noreply.github.com"
            -   name: "Debug: list dist contents"
                run: ls -R dist

            -   name: Deploy to gh-pages
                run: |
                    npx angular-cli-ghpages --dir=dist/DigiAgriFoodDB
                env:
                    CI: true
                    GH_TOKEN: ${{ secrets.GH_TOKEN }}
